### ISSUE TITLE
Alignment method for Text notes (ctrl + w)

### ISSUE THREAD

**Issue by podeynp** [johnpierson/MonocleForDynamo#12]
**What is the problem that needs solving?**
I wish to be able to utilize the alignment tools that are available for nodes, with the text notes. 

**How would you like to see it solved?**
I would like it to operate in the same way that it does currently for the nodes, either a selection and the tool appears or through the quick access toolbar. 

**Describe alternatives you've considered**
(Please fill in if applicable. A clear and concise description of any alternative solutions or features you've considered.)

**Additional context**
(Please fill in if applicable. Add any other context or screenshots about the feature request here.)

**Comment by johnpierson** [comment]
This is fixed for the menu items in the next release.
