### ISSUE TITLE
Shortcut Ctrl+F to open SimpleSearch ve

### ISSUE THREAD

**Issue by Thomas84** [johnpierson/MonocleForDynamo#13]
**What is the problem that needs solving?**
A faster way to open the SimpleSearch view extension to enter a search term

**How would you like to see it solved?**
A settings file to enter a key combination as shortcut. The Shortcut (for example CTRL+F) should open SimpleSearch, if the SimpleSearch is not already open. It should then delete the old search term, and make search field active so I could start typing without clicking into it.

**Comment by johnpierson** [comment]
FYI, the tilde key ` on most keyboards does the focus and clear textbox option at this time.

![image](https://user-images.githubusercontent.com/15744724/93135973-6947da80-f698-11ea-9555-4dc0e695ac57.png)

**Comment by Thomas84** [comment]
FYI, it is not that easy on a german keyboard to press tilde =)

**Comment by johnpierson** [comment]
I kinda figured. lol

**Comment by johnpierson** [comment]
Feature added in v. 2020.09.30

**Comment by Thomas84** [comment]
great addition, so fast! Thank you!
A small improvement suggestion: If the View Extension is closed, I have to type 2 time CTRL+F (one time to open the VE and one time to activate the search cursor. It would be better if it needs only one time pressing (open VE and activate search).
