### ISSUE TITLE
WISH: Make Simple Search override also work for right click search

### ISSUE THREAD

**Issue by josols** [johnpierson/MonocleForDynamo#17]
**What is the problem that needs solving?**
Make Simple Search override also work for right click search

**How would you like to see it solved?**
Muscle memory wants to use right click search in Dynamo. It would be splendid if the override in Monocle also could override right click search.

**Describe alternatives you've considered**
(Please fill in if applicable. A clear and concise description of any alternative solutions or features you've considered.)

**Additional context**
(Please fill in if applicable. Add any other context or screenshots about the feature request here.)

**Comment by johnpierson** [comment]
Messed with this a little recently. Not finished yet. But it might be possible with a different keyboard shortcut. (Shift+Space _- inspiration from [Davinci Resolve's Fusion Visual Programming Language](https://www.blackmagicdesign.com/products/davinciresolve/fusion)_ )

Note: This is in progress and not available in a build yet. Please do not make purchasing decisions of Monocle based on the below GIF.

![20220317-ssInCanvas2](https://user-images.githubusercontent.com/15744724/158889412-e04d6f44-95ea-41b5-b74a-23b18f0fb7d8.gif)
