### ISSUE TITLE
Monocle - Option to add/remove Custom Color Groups

### ISSUE THREAD

**Issue by Lazarica-t** [johnpierson/MonocleForDynamo#2]
**What is the problem that needs solving?**
Some additional color groups would be useful.

**How would you like to see it solved?**
Add an option to Add/Remove new groups in the Custom Grouping dialog box.

**Additional context**
This is useful when working with a predefined dynamo template that has already set up various groups (more then 6 groups).

**Comment by johnpierson** [comment]
Closing this as these features are not in consideration for a free tool at this time.

**Comment by johnpierson** [comment]
Implemented according to, https://github.com/johnpierson/MonocleForDynamo/issues/4#issuecomment-662507741
