### ISSUE TITLE
Conflict UI with tab page

### ISSUE THREAD

**Issue by chuongmep** [johnpierson/MonocleForDynamo#21]
**Describe the bug**
Conflict UI with tab page

**Steps to Reproduce**
Install Package And Open

**Expected behavior**
(Please fill in. A clear and concise description of what you expected to happen.)

**My setup**
- Operating System: Windows 10 20H2
- Dynamo version: Dynamo Sandbox 2.14.0.3326
- Monocle version: V2021.10.1.0
- Revit version: None

https://user-images.githubusercontent.com/31106432/144348450-79e1ac4d-dcb9-4639-a06f-00b81fd34c5d.mp4

**Comment by johnpierson** [comment]
Thanks for the heads up. I am aware of the issue and have been in touch with the Dynamo Team regarding fixes. 

At this time, 2.13 is still in development so a new monocle release hasn't been published. But, this is what I am proposing at the moment:

https://user-images.githubusercontent.com/15744724/144453922-749f7576-ef17-4878-adb2-2098291bea5b.mp4


Essentially, the icons have been removed from the ribbon and are "semi-contextual". Meaning the list combiner shows up with multiple nodes selected, the converter when one is selected, and so on.


If you are interested in testing I can upload a beta build.

**Comment by chuongmep** [comment]
Looks great, I hope they come soon. Good job.

**Comment by johnpierson** [comment]
Version 2021.12.1 should fix this. 
![image](https://user-images.githubusercontent.com/15744724/145643734-541224d6-6cad-410b-9502-d93698c4f6b2.png)

**Comment by chuongmep** [comment]
Working perfect in my computer, thanks @johnpierson
