### ISSUE TITLE
Highlight custom node - Shortcut key + more vibrant highlight color

### ISSUE THREAD

**Issue by Lazarica-t** [johnpierson/MonocleForDynamo#23]
**What is the problem that needs solving?**
1. Multiple clicks to get to the command.
2. Hard to identify highlighted nodes because of the default green color.

**How would you like to see it solved?**
1. Add a shortcut key.
2. Change highlight color to something more vibrant so it pops even when zoomed out. Thicker lines would also help.

👍

**Comment by johnpierson** [comment]
Going to have to investigate how involved this is with the Dynamo 2.13 UI. In short, I really wish that the team would just allow this.

**Comment by johnpierson** [comment]
This is a small preview of what I am thinking for that 
![image](https://user-images.githubusercontent.com/15744724/149580010-078a7eb9-9536-41da-a63b-b11fc7dc35f3.png)

**Comment by Lazarica-t** [comment]
> This is a small preview of what I am thinking for that ![image](https://user-images.githubusercontent.com/15744724/149580010-078a7eb9-9536-41da-a63b-b11fc7dc35f3.png)
> 
> The unfortunate result of this is it might wipe out your custom settings since it is a new version of the settings

**Comment by Lazarica-t** [comment]
Nice, this will definitely help! 👍 👍 :

**Comment by johnpierson** [comment]
@Lazarica-t  - are you willing and able to "beta" test a new release for me? It represents a pretty big change to the codebase, but includes new features like the one above.

**Comment by Lazarica-t** [comment]
Nice 👍 
Font size for groups has been fixed.
Highlights are definitely much better now and the shortcut works like a charm. 
So far everything worked as intended. 👍 

The only thing that needs updating is the version numbers (they don't match):
![image](https://user-images.githubusercontent.com/49474519/150308205-6e88cd89-90da-4a06-a851-3ce395d96082.png)

**Comment by johnpierson** [comment]
Awesome. Thank you for testing and catching that version number. That should be updated when I got publish too. Excited to get this release out!
