### ISSUE TITLE
Need allow insert node when double click outside text in search same line

### ISSUE THREAD

**Issue by chuongmep** [johnpierson/MonocleForDynamo#26]
**What is the problem that needs solving?**
Need allow insert node when double click outside text location same line like this

**How would you like to see it solved?**
- You can see, some region red color cannot use double click to insert node.
![image](https://user-images.githubusercontent.com/31106432/157578190-bd21c700-f38e-4bad-b8a6-3d17110cbf39.png)
Demo 
![DynamoSandbox_C7nl1acoQZ](https://user-images.githubusercontent.com/31106432/157578708-d3132e50-182a-46b9-bb2c-3f691c2b93ce.gif)

**Comment by johnpierson** [comment]
Good catch! I will get that fixed.
