### ISSUE TITLE
Node alignment icons size amendment

### ISSUE THREAD

**Issue by Amoursol** [johnpierson/MonocleForDynamo#3]
**What is the problem that needs solving?**
The alignment icons for Monocle are AWESOME, but also significantly bigger than the Dynamo equivalent they sit next to. 

**How would you like to see it solved?**
Would be cool to have them aligned size wise - would simply look more cohesive.

**Describe alternatives you've considered**
Sucking it up... ;) 

**Additional context**
![image](https://user-images.githubusercontent.com/12857357/83799271-90434900-a673-11ea-9c74-a25995658566.png)

**Comment by johnpierson** [comment]
ahem... the Dynamo team does not have an image size property on the ShortcutBarItems 🤦‍♂️

**Comment by johnpierson** [comment]
![image](https://user-images.githubusercontent.com/15744724/85157817-9b74a800-b221-11ea-9cb5-8b42043a0b7e.png)
