### ISSUE TITLE
FOCA's Dropdown converter not working

### ISSUE THREAD

**Issue by dsellam** [johnpierson/MonocleForDynamo#36]
**Describe the bug**
When we select dropdown nodes and click on the Converter icons, nothing happens

**My setup**
- Operating System: Windows 10
- Dynamo version: 2.12
- Monocle version: 2022.9.10
- Revit version: 2022
- Language : French

**Comment by johnpierson** [comment]
Hi there! Sorry about that. What kind of dropdown are you trying to convert?

**Comment by dsellam** [comment]
Don't be sorry ! Simple search just blowed my mind yesterday, you deserves rewards for that.

It was a category dropdown, selecting Scope boxes (in french interface)

**Comment by BrenJozi** [comment]
I came here to look for a solution as I also have the same issue - I didn't even know what those buttons did until I watched a video this morning

Operating System: Windows 11
Dynamo version: 2.12
Monocle version: 2022.9.2
Revit version: 2022
Language : English

**Comment by johnpierson** [comment]
I will be looking into this a bit more today.

**Comment by BrenJozi** [comment]
There is no pressure from me, I wondered what the icons were for but managed fine up to now without. If I can help in anyway let me know

**Comment by johnpierson** [comment]
Hmm, I just tried it out myself in 2022 in French and it seems to be working. The biggest consideration of the dropdown converter is, you have to have ran the graph with the categories node first.
![image](https://user-images.githubusercontent.com/15744724/196485018-7abcfeca-9a40-4051-b806-0a0d82dc3574.png)

**Comment by BrenJozi** [comment]
Hi John, it was user error on my part then, after I run the script with just the one node it then converts it to a code block as it should. Will know for next time to run the script first.

**Comment by dsellam** [comment]
It works perfectly once you first run the script once ... Awesome

**Comment by johnpierson** [comment]
Thanks for confirming! I will be adding a notification that tells users when this is the case. (Dropdown not being fulfilled)

**Comment by johnpierson** [comment]
![image](https://user-images.githubusercontent.com/15744724/196742869-4f5b5d05-b19b-4d70-a6cf-7525b0d39c06.png)
