### ISSUE TITLE
settings for company standards

### ISSUE THREAD

**Issue by Thomas84** [johnpierson/MonocleForDynamo#4]
**What is the problem that needs solving?**
settings for colors, name of groups, font size and number of groups

**How would you like to see it solved?**
settings.xml

**Comment by Lazarica-t** [comment]
👍 Highly needed! It's a bit annoying having to set up all the colors and names after an package update

**Comment by johnpierson** [comment]
If anyone wants to share some resources for serializing settings as XML, I am all ears. This isn't something I have done a lot of, and to put it simply, I want it done right. 😁

or if you know anyone who wants to submit a PR, that is great too.

**Comment by johnpierson** [comment]
Closing this as these features are not in consideration for a free tool at this time. If at any point in the future, anyone wants to contribute this revision back to the source code, feel free to do so and re-open this issue.

**Comment by johnpierson** [comment]
_So..._ there is a **Very** early release of this for testing here, [2020.7.21a](https://github.com/johnpierson/MonocleForDynamo/tree/2020.7.21a). If you test it, it is absolutely in "beta" mode and should not be used in production work.

If you download the zip file, **you must right click and unblock it** before placing into your Dynamo library.

**Comment by Lazarica-t** [comment]
Awesome! Works like a charm!

![image](https://user-images.githubusercontent.com/49474519/88192975-cf3e5580-cc45-11ea-970f-fbd9e0dd0792.png)

**Comment by johnpierson** [comment]
@Lazarica-t Awesome! Glad to hear that. 

_Also, I see you found the top-secret feature to add more._ 👀

**Comment by Lazarica-t** [comment]
> 
> 
> @Lazarica-t Awesome! Glad to hear that.
> 
> _Also, I see you found the top-secret feature to add more._ 👀

Yes yes! The .xml is very intuitive and simple to use.
Really great job!
