### ISSUE TITLE
Feature Allow Quick Save Backup

### ISSUE THREAD

**Issue by chuongmep** [johnpierson/MonocleForDynamo#40]
**What is the problem that needs solving?**

Just small thing but I think will help for a lot of people 

**How would you like to see it solved?**

- A button allows user to quick save to new version backup with setting include Script Name, date, month, year.
![ảnh](https://user-images.githubusercontent.com/31106432/228468460-24e868cd-bb58-43b7-8073-a10bfda22270.png)

**Describe alternatives you've considered**
(Please fill in if applicable. A clear and concise description of any alternative solutions or features you've considered.)

**Additional context**
(Please fill in if applicable. Add any other context or screenshots about the feature request here.)

**Comment by johnpierson** [comment]
I love it. Will add it to my todo list!
