### ISSUE TITLE
Package detection for lesser used packages

### ISSUE THREAD

**Issue by aussieBIMguru** [johnpierson/MonocleForDynamo#5]
**What is the problem that needs solving?**
Lesser used/known packages don't report their package source.

**How would you like to see it solved?**
Provide documentation on how package managers can set up their nodes to be detected. An example include Topologic BIM. This package is downloaded separately, so is it maybe related to the origin of the package not being on the manager?

**Describe alternatives you've considered**
The package usage dog works, but Clippy/right click don't seem to detect these nodes. Assume they must be sourcing the origin differently.

![issue](https://user-images.githubusercontent.com/58870499/84335884-427d9200-abd9-11ea-8304-240b6134a7ca.PNG)

**Comment by johnpierson** [comment]
For the time being, the lookup primarily works on Package manager packages. It's a lookup dictionary embedded in the library that it parses, so it is fairly "manual" at this time, unfortunately.

Let me add Topologic to the list.

- [ ] Add topologic to lookup.

**Comment by johnpierson** [comment]
Closing this as the Built-In [Workspace References](https://github.com/DynamoDS/Dynamo/tree/master/src/WorkspaceDependencyViewExtension) utility does this now.
