### ISSUE TITLE
Run Warning- Warn Users Before a Computational Heavy Dynamo Run

### ISSUE THREAD

**Issue by johnpierson** [johnpierson/MonocleForDynamo#50]
**What is the problem that needs solving?**
USer has a graph that might take a while. Lots of transaction nodes, etc. Would be nice to have a warning. Also if an endless loop might happen.

**How would you like to see it solved?**
A popup warning when a graph is about to be run.

**Describe alternatives you've considered**
Waiting for the Dynamo team to add.

**Additional context**

**Comment by andydandy74** [comment]
Include a (deployable) option to have this disabled by default. Please. ;-)
