### ISSUE TITLE
Pick Path won't let me paste in a path - makes me work for it every time! 

### ISSUE THREAD

**Issue by lillismith** [johnpierson/MonocleForDynamo#51]
**Describe the bug**
Node Documenter - pick path - paste in a path - won't accept it, makes me manually browse to it every time

**Steps to Reproduce**
(Please fill in. What did you do, step by step?)

**Expected behavior**
(Please fill in. A clear and concise description of what you expected to happen.)

**My setup**
- Operating System: ................
- Dynamo version: ................
- Monocle version: ................
- Revit version: ................
![Snag_c3d024b0](https://github.com/johnpierson/MonocleForDynamo/assets/2932690/ef7b41dc-a95b-4040-8440-77d32496136f)

**Comment by johnpierson** [comment]
lol. This bugs me too!!  I will get it fixed. :)
