### ISSUE TITLE
Settings is reset automaticly

### ISSUE THREAD

**Issue by Tanke806** [johnpierson/MonocleForDynamo#52]
**Describe the bug**
The custom settings of monochle are not retained, seems like the reset default settings runs each time i start dynamo, happens in Dynamo sand box, Dynamo C3D, and Dynamo Revit

**Steps to Reproduce**
Create new settings, or load settings from path and save current settings to default path, (even if you overwrite in windows the default file with the custom settings file), close and launch again Dynamo you start with the default settings with boring colors :(

**Expected behavior**
I hope my settings will be retained, and no have to reload each time!!

**My setup**
- Operating System: Windows
- Dynamo version: 2.15.1.6076
- Monocle version: 2023.11.1.0
- Revit version: 
- 23.1.20.70
- 20230510_1100(x64)
- 2023.1.2
- C3D version
- 13.5.1222.0
- 2023.2.3

**Comment by johnpierson** [comment]
I will check it out!

**Comment by Tanke806** [comment]
By the way I just finished your course, teacher, I am following your steps and practicing to create a package, great job!!

**Comment by johnpierson** [comment]
> By the way I just finished your course, teacher, I am following your steps and practicing to create a package, great job!!

That is awesome to hear! Thanks for checking out the course.

I am working on Monocle updates this week, so let me get this settings stuff sorted at the same time.
