### ISSUE TITLE
Package does not run properly

### ISSUE THREAD

**Issue by AJ-tsumiki** [johnpierson/MonocleForDynamo#55]
**Describe the bug**
I installed the latest package from Dynamo, but when I restart Revit & Dynamo, Monocle is missing from the Dynamo menu and is not useable.

**Steps to Reproduce**
I have followed the procedure described above.
Furthermore, after installing the package, using the package usage tool from the menu Monocle, Dynamo shows up on the report screen with a system error.
Attached is a file of the error report. 
[8.zip](https://github.com/user-attachments/files/16264140/8.zip)

**Expected behavior**

**My setup**
- Operating System: Windows

- Dynamo version: Dynamo Core 2.19.3.6394、Dynamo Revit 2.19.4.11865
- Monocle version: 2024.5.2
- Revit version: 2024.2.1

**Comment by johnpierson** [comment]
Give the latest a try. It should be working.

**Comment by AJ-tsumiki** [comment]
@johnpierson 
I have no choice but to use 2023 for my work on this matter, but there seems to be a problem even with the latest version.

**Comment by johnpierson** [comment]
What is happening exactly? And what revit update do you have precisely?

**Comment by AJ-tsumiki** [comment]
When I close Dynamo, the Monocle tool disappears from the menu.
However, if I delete all folders except the Packages folder in the path below, and then restart Dynamo, the Monocle tool appears in the menu.
C:\Users\username\AppData\Roaming\Dynamo\Dynamo Revit\2.16

Revit version: 2023.1.5 (Japanese)

**Comment by johnpierson** [comment]
That’s helpful to know. I’ll check it out.

**Comment by johnpierson** [comment]
@AJ-tsumiki - can you try the latest version now? 2024.12.2

**Comment by AJ-tsumiki** [comment]
@johnpierson The situation remains the same, it appears only during the first installation and disappears after a reboot..
![image](https://github.com/user-attachments/assets/bf0bfe22-dcab-4a2c-ab3e-dbe9481fa944)

**Comment by AJ-tsumiki** [comment]
It seems that once the data in "DynamoSettings.xml" is deleted, it will appear in the menu.
