### ISSUE TITLE
Group selection/update behavior

### ISSUE THREAD

**Issue by aussieBIMguru** [johnpierson/MonocleForDynamo#6]
**Describe the bug**
Group selection updates last created group, even with no selections made, or a pre-existing group selected.

**Steps to Reproduce**
1. Create groups using the eyedropper on selection
2. Deselect nodes or select another group
3. Last created group updates

**Expected behavior**
The group selected function should ideally only run if a user has a group or set of un-grouped elements currently selected I think.

**My setup**
- Operating System: Win10
- Dynamo version: 2.3
- Monocle version: 2020.6.1
- Revit version: 2020.2.1

**Comment by johnpierson** [comment]
I have seen this with the full UI window one as well. It has been a hard one to track and I haven't been able to pin it down quite yet. 🤔

**Comment by johnpierson** [comment]
This _seem_ to be fixed in the newest version since I overhauled the backend code.
