### ISSUE TITLE
Custom package filtering to simple search

### ISSUE THREAD

**Issue by aussieBIMguru** [johnpierson/MonocleForDynamo#8]
**What is the problem that needs solving?**
Toggle in simple search to include/exclude custom package nodes. This is really useful when you have a lot of packages installed and are just looking for an OOTB node - can be difficult when the noise of packages is included.

**How would you like to see it solved?**
Tick box 'include custom packages', or alternatively 'exclude custom packages'

**Describe alternatives you've considered**
Scrolling through, or having to be more specific with keyword searching.

![add option](https://user-images.githubusercontent.com/58870499/84336747-4ad6cc80-abdb-11ea-81d0-33dc7a0714e1.PNG)

**Comment by johnpierson** [comment]
This has been addressed in, https://github.com/johnpierson/MonocleForDynamo/releases/tag/2020.07.14
