### ISSUE TITLE
Alternative screen for usage Doge

### ISSUE THREAD

**Issue by aussieBIMguru** [johnpierson/MonocleForDynamo#9]
**What is the problem that needs solving?**
Some users I've shown Monocle too don't have a sense of humor that aligns with the Doge. Consider an alternative profile setting where this page can be set to a 'lite/humorless' alternative. It may also help streamline the use of Monocle in corporate/stale user environments. Sad I know - personally I like it :)

If this goes against the 'spirit' of Monocle I totally understand, just based on what others have told me a few times.

**How would you like to see it solved?**
Alternative UI where doge image is toggled off, or a preference to replace with a different image.

**Describe alternatives you've considered**
Developing a sense of humor!

![lite ui](https://user-images.githubusercontent.com/58870499/84337022-f3852c00-abdb-11ea-9a72-50f9c7dc439a.png)

**Comment by johnpierson** [comment]
I have been waiting for this to come up for quite some time. The "doge" was my funny way of building something that the Dynamo team told me cannot be done at the time. (2 years ago).

Documenting which packages are used was something on my mind for years, so when I finally cracked it, I decided to purposely build a crappy UI. 😁 

I will meditate on if I want to fix this in the future, but for now it stays. 

>You want to lookup packages in the graph? Then you gotta see the doge at first. LOL

**Comment by aussieBIMguru** [comment]
No problems, you're well in your rights to keep the spirit alive.

I love the backstory, wasn't fully aware of the rebellious nature of the doge!

Personally it's what I'd do too, just wanted to give a voice to some of the people who spoke to me about Monocle. Wide spectrum of thinkers out there for sure.

**Comment by johnpierson** [comment]
For sure. And I do think I’ll add an option for if you resize it, that it
will remember that choice for future openings.

**Comment by johnpierson** [comment]
FWIW, the next release will allow you to click on the image of the Doge and it will hide for that instance of the window. The doge also has a new professional look. 🧐 
![image](https://user-images.githubusercontent.com/15744724/85182345-05a34200-b24e-11ea-9745-12c40d453968.png)
